package com.vuavent.audio.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class OrderDAO {
	
	public int insertOrder3(int userid, int total) {
		try {
		DriverManager.registerDriver(new com.mysql.jdbc.Driver());
	      //Getting the connection
	      String mysqlUrl = "jdbc:mysql://localhost:3306/twl_store?characterEncoding=UTF8";
	      Connection con = DriverManager.getConnection(mysqlUrl, "root", "minhvu300499");
	      //Query to Insert values to the sales table
	      String insertQuery = "INSERT INTO orders (userid, total)"
					+ " VALUES (?,?)";
	      //Creating a PreparedStatement object
	      PreparedStatement pstmt = con.prepareStatement(insertQuery,Statement.RETURN_GENERATED_KEYS);
	      pstmt.setInt(1, userid);
	      pstmt.setInt(2, total);
	      pstmt.addBatch();
	      //Executing the batch
	      pstmt.executeBatch();
	      //Auto-incremented values generated by the current PreparedStatement object
	      ResultSet res = pstmt.getGeneratedKeys();
	      System.out.println("Auto-incremented values of the column ID generated: ");
	      while (res.next()) {
	         System.out.println(res.getString(1));
	         String orderidStr = res.getString(1);
	         int orderid = Integer.parseInt(orderidStr);
	         return orderid;
	      }
		}catch(SQLException e) {
	    	  e.printStackTrace();
	      }
		return 0;
	}
}
//	public void insertOrder(int userid, int total) {
//		Connection connection = null;
//		PreparedStatement preparedStatement = null;
//
//		try {
//			connection = ConnectionFactory.getConnection();
//			String insertSQL = "INSERT INTO orders (userid, total)"
//					+ " VALUES (?,?)";
//			preparedStatement = connection.prepareStatement(insertSQL);
//			preparedStatement.setInt(1, userid);
//			preparedStatement.setInt(2, total);
//			preparedStatement.executeUpdate();
//
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//
//	
//	private static Order convertToOrder(ResultSet rs) throws SQLException {
//		Order order = new Order();
//		order.setId(rs.getInt(1));
//		
//
//		return order;
//	}
//}
